name: gifza
description: "Search GIF's and Images with embeddings with Gifza"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider:
  objectbox: ^5.3.1
  dart_sentencepiece_tokenizer: ^1.3.2
  file_picker: 
  executorch_flutter: ^0.3.3
  objectbox_flutter_libs: any
  shared_preferences: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.15.0
  objectbox_generator: any


hooks:
  user_defines:
    executorch_flutter:
      debug: false              
      build_mode: "prebuilt"     
  
      backends:
        - xnnpack
        - coreml
        - mps

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/models/text.pte
    - assets/models/image.pte
    - assets/models/tokenizer.json

  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400

        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500

        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

    - family: Vietnam
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 400

        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
 